spring.application.name=backend
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/Gram_Setu
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
gramsetu.jwt.secret=9a4f2c8d3b7a1e5f0g9h8i7j6k5l4m3n2o1p0q9r8s7t6u5v4w3x2y1z0a1b2c3d
gramsetu.jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
upload.path=uploads/
# Admin Security
gramsetu.admin.secret=GramSetuAdmin123

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false
